name: Docker Image CI

on:
  push:
    branches: [ "OPENGPDB_STABLE", "MDB_6_25_STABLE_YEZZEY" ]
  pull_request:
    branches: [ "OPENGPDB_STABLE", "YGP_6.27_STABLE", "MDB_6_25_STABLE_YEZZEY" ]

jobs:

  build_and_run_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/regress/Dockerfile --tag regress_test:1234 && docker run regress_test:1234
    
    - name: Check and Display Regression Diffs
      if: always()
      run: |
          # Search for regression.diffs recursively
          found_file=$(find . -type f -name "regression.diffs" | head -n 1)
          if [[ -n "$found_file" ]]; then
            echo "Found regression.diffs at: $found_file"
            cat "$found_file"
          else
            echo "No regression.diffs file found in the hierarchy."
          fi

