name: Regresstion testing

on:
  push:
    branches: [ "OPENGPDB_STABLE", "MDB_6_25_STABLE_YEZZEY" ]
  pull_request:
    branches: [ "OPENGPDB_STABLE", "YGP_6.27_STABLE", "MDB_6_25_STABLE_YEZZEY" ]

jobs:

  build_and_run_test:

    runs-on: ubuntu-latest

    steps:
    - name: Check disk space
      run: df . -h

    - name: Free disk space
      run: |
        sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
        sudo rm -rf \
          /usr/share/dotnet /usr/local/lib/android /opt/ghc \
          /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
          /usr/lib/jvm || true
        echo "some directories deleted"
        sudo apt install aptitude -y >/dev/null 2>&1
        sudo aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync \
          esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
          google-cloud-sdk imagemagick \
          libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
          mercurial apt-transport-https mono-complete libmysqlclient \
          unixodbc-dev yarn chrpath libssl-dev libxft-dev \
          libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
          snmp pollinate libpq-dev postgresql-client powershell ruby-full \
          sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable \
          -y -f >/dev/null 2>&1
        sudo aptitude purge google-cloud-sdk -f -y >/dev/null 2>&1
        sudo aptitude purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
        sudo apt purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
        sudo aptitude purge '~n ^mysql' -f -y >/dev/null 2>&1
        sudo aptitude purge '~n ^php' -f -y >/dev/null 2>&1
        sudo aptitude purge '~n ^dotnet' -f -y >/dev/null 2>&1
        sudo apt-get autoremove -y >/dev/null 2>&1
        sudo apt-get autoclean -y >/dev/null 2>&1
        echo "some packages purged"
    - name: Check disk space
      run: |
        sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
        df . -h
        sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head

    - uses: actions/checkout@v4

    - name: Build
      run: docker build . --file docker/regress/Dockerfile --tag regress_test:1234

    - name: Run Regression Tests
      run: docker run --name regress_test_container regress_test:1234

    - name: Get Regression Diffs from Docker Container
      if: always()
      run: |
          docker ps -a
          docker cp regress_test_container:/home/krebs/src/test/regress/regression.diffs regression.diffs

    - name: Check and Display Regression Diffs
      if: always()
      run: |
          # Search for regression.diffs recursively
          found_file=$(find . -type f -name "regression.diffs" | head -n 1)
          if [[ -n "$found_file" ]]; then
            echo "Found regression.diffs at: $found_file"
            cat "$found_file"
          else
            echo "No regression.diffs file found in the hierarchy."
            cat /home/krebs/src/test/regress/regression.diffs
          fi

    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: regress-test-report
        path: regression.diffs

    - name: Check disk space
      if: always()
      run: |
        sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
        df . -h
        sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head

  installcheck-parallel-retrieve-cursor:

    runs-on: ubuntu-latest

    steps:
    - name: Check disk space
      run: df . -h

    - name: Free disk space
      run: |
        sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
        sudo rm -rf \
          /usr/share/dotnet /usr/local/lib/android /opt/ghc \
          /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
          /usr/lib/jvm || true
        echo "some directories deleted"
        sudo apt install aptitude -y >/dev/null 2>&1
        sudo aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync \
          esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
          google-cloud-sdk imagemagick \
          libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
          mercurial apt-transport-https mono-complete libmysqlclient \
          unixodbc-dev yarn chrpath libssl-dev libxft-dev \
          libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
          snmp pollinate libpq-dev postgresql-client powershell ruby-full \
          sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable \
          -y -f >/dev/null 2>&1
        sudo aptitude purge google-cloud-sdk -f -y >/dev/null 2>&1
        sudo aptitude purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
        sudo apt purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
        sudo aptitude purge '~n ^mysql' -f -y >/dev/null 2>&1
        sudo aptitude purge '~n ^php' -f -y >/dev/null 2>&1
        sudo aptitude purge '~n ^dotnet' -f -y >/dev/null 2>&1
        sudo apt-get autoremove -y >/dev/null 2>&1
        sudo apt-get autoclean -y >/dev/null 2>&1
        echo "some packages purged"
    - name: Check disk space
      run: |
        sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
        df . -h
        sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head

    - uses: actions/checkout@v4

    - name: Build
      run: docker build . --file docker/parallel_retrieve_cursor/Dockerfile --tag prc_test:1234

    - name: Run Regression Tests
      run: docker run --name prc_test_container prc_test:1234

    - name: Get Regression Diffs from Docker Container
      if: always()
      run: |
          docker ps -a
          docker cp prc_test_container:/home/krebs/src/test/isolation2/regression.diffs regression.diffs || touch regression.diffs

    - name: Check and Display Regression Diffs
      if: always()
      run: |
          # Search for regression.diffs recursively
          found_file=$(find . -type f -name "regression.diffs" | head -n 1)
          if [[ -n "$found_file" ]]; then
            echo "Found regression.diffs at: $found_file"
            cat "$found_file"
          else
            echo "No regression.diffs file found in the hierarchy."
            cat /home/krebs/src/test/isolation2/regression.diffs
          fi

    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: regress-test-report
        path: regression.diffs

    - name: Check disk space
      if: always()
      run: |
        sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
        df . -h
        sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head

